Fix Parser for ModuleIdentificationRequest of s7 Protocol
zmap/zgrab2 pull request #423
Opened 2024-04-17 05:56 UTC by developStorm

Rewrote response parser with information provided in the issue. Resolves #212. 

Tested against some real S7 modules and _appears_ to work, absolutely makes more sense than the original code. However, would be great if we can confirm on a device we control.

2024-04-17 16:48 UTC, phillip-stephens commented
@zakird Does Censys have any Siemens S7 PLC's we could use for testing/validation?

2024-04-17 20:39 UTC, phillip-stephens requested changes
minor nitpicks, looks great overall for code quality + documentation. 

To be perfectly honest, I've been unable to convince myself that I understand the `Index W#16#XY` format that Siemens is using and haven't found any guides online. Like for example, `Index W#16#0006 and W#16#0007: remaining numbers of the version ID`, does this refer to bits 6 and 7? The use of the word "index" makes me think it's referring to a specific bit in the word, but that seems very arbitrary for a 16 bit value. I'm unsure what else it could mean, but also don't feel confident in it being bits 6 and 7.

If you found some better explanations in your digging, lmk, otherwise IMO we should wait for a real Siemens device to test against to confirm understanding.

2024-04-17 22:53 UTC, developStorm commented on modules/siemens/s7.go
> +			logStruct.Firmware = getVersionNumber(record)
I have no clue how I left the code like that 🤣 it looks very weird in retrospect

2024-04-22 18:58 UTC, phillip-stephens approved these changes
LGTM, thanks for your work on this

2024-04-22 18:58 UTC, merged

2024-04-23 22:50 UTC, developStorm commented
@Valentinbist Thank you for sharing all these details! These are really helpful and we'll patch our parser accordingly soon. Btw, did the `unknown11` field help in your analysis of your scan results? Do you think it would be good if we were to include it in ZGrab output?